# Generated by Django 4.2.7 on 2023-12-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lifeapp', '0002_expense_patient_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='AccountRecievable',
        ),
    ]
