# Generated by Django 4.2.7 on 2023-12-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lifeapp', '0003_rename_vendor_accountrecievable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
