# Generated by Django 4.2.7 on 2024-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lifeapp', '0007_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Account', models.CharField(max_length=255)),
                ('Debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
