# Generated by Django 4.2.7 on 2024-01-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lifeapp', '0008_generalledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='Credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='Debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
